const { TYPE_MAP, DEFAULT_VALUES, toPascalCase, toClassName } = require('./types.cjs');

/**
 * Generate C# partial class (.gen.cs) from a NodeDefinition.
 */
function generate(def, edges, nodeMap) {
  const cs = TYPE_MAP.csharp;
  const dv = DEFAULT_VALUES.csharp;
  const className = toClassName(def.type);
  const isOneShot = !def.pins?.outputs?.length;

  // ── Pins ──
  const pins = [];
  for (const input of (def.pins?.inputs || [])) {
    pins.push(`    public const string In_${toPascalCase(input.id)} = "${input.id}";`);
  }
  for (const output of (def.pins?.outputs || [])) {
    pins.push(`    public const string Out_${toPascalCase(output.id)} = "${output.id}";`);
  }

  // ── Params ──
  const fields = [];
  const ctors = [];
  for (const p of (def.params || [])) {
    const t = cs[p.type] || 'string';
    const prop = toPascalCase(p.key);
    const defVal = JSON.stringify(p.default);
    fields.push(`    public Param<${t}> ${prop} { get; }`);
    ctors.push(`        ${prop} = new Param<${t}>(
            _source("${p.key}"),
            _value<${t}>("${p.key}", ${defVal}),
            _paramKey("${p.key}"));`);
  }

  // ── Outs ──
  const outFields = [];
  const setOutCases = [];
  for (const output of (def.pins?.outputs || [])) {
    const fieldName = 'Out' + toPascalCase(output.id);
    outFields.push(`    public INodeHandler? ${fieldName};`);
    setOutCases.push(`            case "${output.id}": ${fieldName} = target; break;`);
  }
  const hasOuts = setOutCases.length > 0;

  // ── OnTick default ──
  const onTickBody = isOneShot
    ? '        // One-shot: completes immediately\n        return NodeStatus.Complete;'
    : '        // Override in partial class\n        return NodeStatus.Running;';

  // ── Assemble ──
  return `// ⚠️ AUTO-GENERATED by FlowForge CLI — DO NOT EDIT
// Source: ${def.type} (${def.label})
// Generated: ${new Date().toISOString()}

using System.Text.Json;
using FlowForge.Runtime;

namespace FlowForge.Generated;

public partial class ${className} : INodeHandler, IWireOuts, INodeDataReceiver
{
    // ── Pins ──
${pins.join('\n')}

    // ── Params ──
${fields.join('\n')}

    // ── Node data ──
    private JsonElement _nodeData;
${hasOuts ? '\n    // ── Outs ──\n' + outFields.join('\n') + '\n' : ''}
    // ── Lifecycle ──
    public virtual void OnEnter(IRuntime rt) { }

    public virtual NodeStatus OnTick(IRuntime rt, float delta)
    {
${onTickBody}
    }

    public virtual void OnExit(IRuntime rt) { }
${hasOuts ? `
    // ── IWireOuts ──
    public void SetOut(string pinId, INodeHandler target)
    {
        switch (pinId)
        {
${setOutCases.join('\n')}
        }
    }

    public void ResolveOuts(IReadOnlyDictionary<string, INodeHandler> _) { }
` : `
    // ── IWireOuts ──
    public void SetOut(string pinId, INodeHandler target) { }
    public void ResolveOuts(IReadOnlyDictionary<string, INodeHandler> _) { }
`}
    // ── INodeDataReceiver ──
    public void ReceiveNodeData(JsonElement nodeJson) => _nodeData = nodeJson;

    // ── Helpers ──
    private string _source(string key) =>
        _nodeData.TryGetProperty("params", out var ps) &&
        ps.TryGetProperty(key, out var p) &&
        p.TryGetProperty("source", out var s)
            ? s.GetString()! : "fixed";

    private T _value<T>(string key, T deflt) =>
        _nodeData.TryGetProperty("params", out var ps) &&
        ps.TryGetProperty(key, out var p) &&
        p.TryGetProperty("value", out var v)
            ? Parse<T>(v, deflt) : deflt;

    private string? _paramKey(string key) =>
        _source(key) == "param"
            ? _nodeData.TryGetProperty("params", out var ps) &&
              ps.TryGetProperty(key, out var p) &&
              p.TryGetProperty("value", out var v)
                ? v.GetString() : null
            : null;

    private static T Parse<T>(JsonElement el, T fallback)
    {
        try { return (T)(object)(el.ValueKind switch {
            JsonValueKind.String => el.GetString()!,
            JsonValueKind.Number => typeof(T) == typeof(float)
                ? (float)el.GetDouble()
                : (int)el.GetInt64(),
            JsonValueKind.True  => true,
            JsonValueKind.False => false,
            _ => fallback!
        }); }
        catch { return fallback; }
    }
}
`;
}

/**
 * Generate .gen.cs files from NodeDefinition[] and save to outDir.
 */
function generateAll(defs, edges, outDir) {
  const fs = require('fs');
  const path = require('path');
  if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });

  const generated = [];
  for (const def of defs) {
    const code = generate(def, edges);
    const fileName = `${def.type
      .split('_')
      .map(w => w.charAt(0).toUpperCase() + w.slice(1))
      .join('')}Node.gen.cs`;
    fs.writeFileSync(path.join(outDir, fileName), code, 'utf-8');
    generated.push(fileName);
  }
  return generated;
}

module.exports = { generate, generateAll };
