// ⚠️ AUTO-GENERATED by FlowForge CLI — DO NOT EDIT
// Source: flow_start (flow_start)
// Generated: 2026-07-05T11:41:26.026Z

using System.Text.Json;
using FlowForge.Runtime;

namespace FlowForge.Generated;

public partial class FlowStartNode : INodeHandler, IWireOuts, INodeDataReceiver
{
    // ── Pins ──
    public const string In_FlowIn = "flow_in";
    public const string Out_FlowOut = "flow_out";

    // ── Params ──


    // ── Node data ──
    private JsonElement _nodeData;

    // ── Outs ──
    public INodeHandler? OutFlowOut;

    // ── Lifecycle ──
    public virtual void OnEnter(IRuntime rt) { }

    public virtual NodeStatus OnTick(IRuntime rt, float delta)
    {
        // Override in partial class
        return NodeStatus.Running;
    }

    public virtual void OnExit(IRuntime rt) { }

    // ── IWireOuts ──
    public void SetOut(string pinId, INodeHandler target)
    {
        switch (pinId)
        {
            case "flow_out": OutFlowOut = target; break;
        }
    }

    public void ResolveOuts(IReadOnlyDictionary<string, INodeHandler> _) { }

    // ── INodeDataReceiver ──
    public void ReceiveNodeData(JsonElement nodeJson) => _nodeData = nodeJson;

    // ── Helpers ──
    private string _source(string key) =>
        _nodeData.TryGetProperty("params", out var ps) &&
        ps.TryGetProperty(key, out var p) &&
        p.TryGetProperty("source", out var s)
            ? s.GetString()! : "fixed";

    private T _value<T>(string key, T deflt) =>
        _nodeData.TryGetProperty("params", out var ps) &&
        ps.TryGetProperty(key, out var p) &&
        p.TryGetProperty("value", out var v)
            ? Parse<T>(v, deflt) : deflt;

    private string? _paramKey(string key) =>
        _source(key) == "param"
            ? _nodeData.TryGetProperty("params", out var ps) &&
              ps.TryGetProperty(key, out var p) &&
              p.TryGetProperty("value", out var v)
                ? v.GetString() : null
            : null;

    private static T Parse<T>(JsonElement el, T fallback)
    {
        try { return (T)(object)(el.ValueKind switch {
            JsonValueKind.String => el.GetString()!,
            JsonValueKind.Number => typeof(T) == typeof(float)
                ? (float)el.GetDouble()
                : (int)el.GetInt64(),
            JsonValueKind.True  => true,
            JsonValueKind.False => false,
            _ => fallback!
        }); }
        catch { return fallback; }
    }
}
