//! C# code generator. Converts parsed `NodeDefinition` → `.gen.cs` partial class.

use crate::code_generator::parser::NodeDefinition;

// ── Helpers ──

fn type_map(dsl_type: &str) -> &str {
    match dsl_type {
        "string" | "text" | "enum" => "string",
        "number" => "int",
        "float" => "float",
        "boolean" => "bool",
        _ => "string",
    }
}

fn default_expr(dsl_type: &str, val: Option<&serde_json::Value>) -> String {
    match val {
        Some(v) => match v {
            serde_json::Value::String(s) => format!("\"{}\"", s.replace('"', "\\\"")),
            serde_json::Value::Number(n) => {
                if dsl_type == "float" {
                    let f: f64 = n.as_f64().unwrap_or(0.0);
                    format!("{}f", f)
                } else {
                    n.to_string()
                }
            }
            serde_json::Value::Bool(b) => {
                if *b { "true".into() } else { "false".into() }
            }
            _ => default_expr(dsl_type, None),
        },
        None => match dsl_type {
            "string" | "text" | "enum" => "\"\"".into(),
            "number" => "0".into(),
            "float" => "0f".into(),
            "boolean" => "false".into(),
            _ => "\"\"".into(),
        },
    }
}

pub fn to_pascal_case(s: &str) -> String {
    let mut result = String::new();
    let mut capitalize = true;
    for c in s.chars() {
        if c == '_' {
            capitalize = true;
        } else if capitalize {
            result.push(c.to_ascii_uppercase());
            capitalize = false;
        } else {
            result.push(c);
        }
    }
    result
}

fn class_name(node_type: &str) -> String {
    format!("{}Node", to_pascal_case(node_type))
}

// ── Generator ──

pub fn generate(def: &NodeDefinition) -> String {
    let cls = class_name(&def.node_type);
    let has_outputs = !def.pins.outputs.is_empty();

    // Pins section
    let pins: Vec<String> = def
        .pins
        .inputs
        .iter()
        .map(|p| format!("    public const string In_{0} = \"{1}\";", to_pascal_case(&p.id), p.id))
        .chain(
            def.pins.outputs.iter().map(|p| {
                format!("    public const string Out_{0} = \"{1}\";", to_pascal_case(&p.id), p.id)
            }),
        )
        .collect();

    // Params section
    let mut fields: Vec<String> = Vec::new();
    let mut ctors: Vec<String> = Vec::new();
    for p in &def.params {
        let t = type_map(&p.param_type);
        let prop = to_pascal_case(&p.key);
        let def_val = default_expr(&p.param_type, p.default.as_ref());
        fields.push(format!("    public Param<{0}> {1} {{ get; }}", t, prop));
        ctors.push(format!(
            "        {0} = new Param<{1}>(\n            _source(\"{2}\"),\n            _value<{1}>(\"{2}\", {3}),\n            _paramKey(\"{2}\"));",
            prop, t, p.key, def_val
        ));
    }

    // Outs section
    let mut out_fields: Vec<String> = Vec::new();
    let mut set_out_cases: Vec<String> = Vec::new();
    for o in &def.pins.outputs {
        let fname = format!("Out{}", to_pascal_case(&o.id));
        out_fields.push(format!("    public INodeHandler? {0};", fname));
        set_out_cases.push(format!(
            "            case \"{0}\": {1} = target; break;",
            o.id, fname
        ));
    }

    // OnTick default
    let on_tick_body = if has_outputs {
        "        // Override in partial class\n        return NodeStatus.Running;"
    } else {
        "        // One-shot: completes immediately\n        return NodeStatus.Complete;"
    };

    // ── WireOuts section ──
    let wire_outs = if has_outputs {
        format!(
            "
    // ── IWireOuts ──
    public void SetOut(string pinId, INodeHandler target)
    {{
        switch (pinId)
        {{
{0}
        }}
    }}

    public void ResolveOuts(IReadOnlyDictionary<string, INodeHandler> _) {{ }}
",
            set_out_cases.join("\n")
        )
    } else {
        "
    // ── IWireOuts ──
    public void SetOut(string pinId, INodeHandler target) { }
    public void ResolveOuts(IReadOnlyDictionary<string, INodeHandler> _) { }
"
        .to_string()
    };

    // ── Out section ──
    let out_section = if has_outputs {
        format!(
            "
    // ── Outs ──
{0}
",
            out_fields.join("\n")
        )
    } else {
        String::new()
    };

    // ── Assemble ──
    format!(
        r#"// ⚠️ AUTO-GENERATED by FlowForge — DO NOT EDIT
// Source: {node_type} ({label})

using System.Text.Json;
using FlowForge.Runtime;

namespace FlowForge.Generated;

public partial class {class_name} : INodeHandler, IWireOuts, INodeDataReceiver
{{
    // ── Pins ──
{pins}

    // ── Params ──
{fields}

    // ── Node data ──
    private JsonElement _nodeData;{out_section}
    // ── Constructor ──
    public {class_name}()
    {{
{ctors}
    }}
{wire_outs}
    // ── INodeDataReceiver ──
    public void ReceiveNodeData(JsonElement nodeJson) => _nodeData = nodeJson;

    // ── Lifecycle ──
    public virtual void OnEnter(IRuntime rt) {{ }}

    public virtual NodeStatus OnTick(IRuntime rt, float delta)
    {{
{on_tick_body}
    }}

    public virtual void OnExit(IRuntime rt) {{ }}

    // ── Helpers ──
    private string _source(string key) =>
        _nodeData.TryGetProperty("params", out var ps) &&
        ps.TryGetProperty(key, out var p) &&
        p.TryGetProperty("source", out var s)
            ? s.GetString()! : "fixed";

    private T _value<T>(string key, T deflt) =>
        _nodeData.TryGetProperty("params", out var ps) &&
        ps.TryGetProperty(key, out var p) &&
        p.TryGetProperty("value", out var v)
            ? Parse<T>(v, deflt) : deflt;

    private string? _paramKey(string key) =>
        _source(key) == "param"
            ? _nodeData.TryGetProperty("params", out var ps) &&
              ps.TryGetProperty(key, out var p) &&
              p.TryGetProperty("value", out var v)
                ? v.GetString() : null
            : null;

    private static T Parse<T>(JsonElement el, T fallback)
    {{
        try {{ return (T)(object)(el.ValueKind switch {{
            JsonValueKind.String => el.GetString()!,
            JsonValueKind.Number => typeof(T) == typeof(float)
                ? (float)el.GetDouble()
                : (int)el.GetInt64(),
            JsonValueKind.True  => true,
            JsonValueKind.False => false,
            _ => fallback!
        }}); }}
        catch {{ return fallback; }}
    }}
}}
"#,
        node_type = def.node_type,
        label = def.label,
        class_name = cls,
        pins = if pins.is_empty() { "    // (none)".into() } else { pins.join("\n") },
        fields = if fields.is_empty() { "    // (none)".into() } else { fields.join("\n") },
        out_section = out_section,
        ctors = if ctors.is_empty() { "        // (none)".into() } else { ctors.join("\n") },
        wire_outs = wire_outs.trim(),
        on_tick_body = on_tick_body,
    )
}
